image: java:8

stages:
     - build
     - test
     - deploy
     - package
before_script:
     - chmod +x mvnw
     
build:
    stage: build
    script: ./mvnw -B -Dskip.surefire.tests clean package
    artifacts:
      paths:
       - target/TravelService-0.0.1-SNAPSHOT.jar
unit-test:
     stage: test
     script: ./mvnw test
     artifacts:
       reports:
         junit:
           - target/surefire-reports/TEST-*.xml
     
integration-test:  
     stage: test
     script: ./mvnw verify -Dskip.surefire.tests -e
    
docker_push:
  stage: package
  image: docker:latest
  services:
   - docker:dind
  script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - docker build -t eicke74/travelmanager .
   - docker push eicke74/travelmanager:latest
  