

spring:
  profiles: development

  data:
    mongodb:
      datasbase: meineDatenbank
---
spring:
  profiles: test

  data:
    mongodb:
      database: testDB
  
---
spring:
  profiles: openshift

  data:
    mongodb:
      uri: ${OPENSHIFT_MONGODB_DB_URL}
      database: sampledb
  