security.oauth2.resource.userInfoUri: http://localhost:8081/auth/user
security.user.password: geheim
security.user.name: eicke
server.context-path: /travelmanager 
logging.level.org.springframework: DEBUG
test.value: true
server.port: 9020
---
spring:
  profiles: development

  data:
    mongodb:
      database: meineDatenbank
---
spring:
  profiles: test

  data:
    mongodb:
      database: testDB
  
---
spring:
  profiles: openshift

  data:
    mongodb:
      uri: ${MONGO_URL}
      database: meineProdDB
      
  